# Generated by Django 4.2.2 on 2023-07-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='members',
            new_name='seller',
        ),
    ]
