# Generated by Django 4.2.2 on 2023-07-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_members_conversation_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='seller',
            new_name='member',
        ),
    ]
