# Generated by Django 4.2.2 on 2023-07-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_rename_seller_conversation_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='member',
            new_name='members',
        ),
    ]
