# Generated by Django 4.2.2 on 2023-07-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_crated_by_item_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
